# This specifically stops the 'No spring.config.import property' check
spring.cloud.config.import-check.enabled=false

# Keep your current settings
spring.application.name=gateway
spring.cloud.config.enabled=false
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=8080

# JWT Configuration (Base64 encoded - must match userservice)
rsa.private-key=classpath:private.key
rsa.public-key=classpath:public.key
